CREATE DATABASE DATA_DUAN
GO
USE DATA_DUAN
GO

-- LoaiSanPham
CREATE TABLE LOAISANPHAM(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MA VARCHAR(20) UNIQUE,
TEN NVARCHAR(30)
)

-- SANPHAM
CREATE TABLE SANPHAM(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IDLOAISP UNIQUEIDENTIFIER,
MASP VARCHAR(20) UNIQUE,
TENSP NVARCHAR(50) DEFAULT NULL,
SOLUONG INT,
HINHANH NVARCHAR(50) DEFAULT NULL,
SIZE NVARCHAR(50) DEFAULT NULL,
MAUSAC NVARCHAR(50) DEFAULT NULL,
CHATLIEU NVARCHAR(50) DEFAULT NULL,
GIANHAP DECIMAL(20,0) DEFAULT 0,
GIABAN DECIMAL(20,0) DEFAULT 0,
)

ALTER TABLE SANPHAM ADD FOREIGN KEY(IDLOAISP) REFERENCES LOAISANPHAM(ID)

-- NhanVien
CREATE TABLE NHANVIEN(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MANV VARCHAR(20) UNIQUE,
HOTEN NVARCHAR(30) DEFAULT NULL,
GIOITINH NVARCHAR(30) DEFAULT NULL,
NgaySinh DATE DEFAULT NULL,
DIACHI NVARCHAR(100) DEFAULT NULL,
SDT VARCHAR(30) DEFAULT NULL,
TENTAIKHOAN NVARCHAR(100) DEFAULT NULL,
MATKHAU VARCHAR(MAX) DEFAULT NULL,
TrangThai INT DEFAULT 0
)

-- KhachHang
CREATE TABLE KhachHang(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MAKH int IDENTITY(1,1) ,
HOTEN NVARCHAR(30),
GIOITINH NVARCHAR(30) DEFAULT NULL,
NGAYSINH DATE DEFAULT NULL,
SDT VARCHAR(30) DEFAULT NULL,
DIACHI NVARCHAR(100) DEFAULT NULL,
THANHPHO NVARCHAR(50) DEFAULT NULL,
QUOCGIA NVARCHAR(50) DEFAULT NULL,
TENTAIKHOAN NVARCHAR(50) DEFAULT NULL,
MATKHAU VARCHAR(MAX) DEFAULT NULL,
NHAPLAIMK VARCHAR(MAX) DEFAULT NULL,
HINHANH NVARCHAR(50) DEFAULT NULL,
)

--KhuyenMai

CREATE TABLE KHUYENMAI(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MA VARCHAR(20) UNIQUE,
TENKM NVARCHAR(30),
NGAYBATDAU DATE DEFAULT NULL,
NGAYKETTHUC DATE DEFAULT NULL,
TrangThai INT DEFAULT 0,
)


CREATE TABLE QUANLYTAIKHOAN(
IDKH UNIQUEIDENTIFIER,
IDNV UNIQUEIDENTIFIER,
TENTK NVARCHAR(30),
MATKHAU VARCHAR (MAX) DEFAULT NULL,
TRANGTHAI INT DEFAULT 0 ,
CONSTRAINT PK_QUANLYTAIKHOAN PRIMARY KEY (IDKH,IDNV),
CONSTRAINT FK1 FOREIGN KEY(IdKH) REFERENCES KhachHang(Id),
CONSTRAINT FK2 FOREIGN KEY(IDNV) REFERENCES NHANVIEN(Id),
)

CREATE TABLE GIOHANG(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IDKH UNIQUEIDENTIFIER,
IDSP UNIQUEIDENTIFIER,
NGAYTHEMVAOGIOHANG DATE DEFAULT NULL,
SOLUONG INT,
DONGIA DECIMAL(20,0) DEFAULT 0,
HINHANH NVARCHAR(50) DEFAULT NULL,
)

ALTER TABLE GIOHANG ADD FOREIGN KEY(IDKH) REFERENCES KhachHang(ID)
ALTER TABLE GIOHANG ADD FOREIGN KEY(IDSP) REFERENCES SANPHAM(ID)

CREATE TABLE HOADONDATHANG(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IDNV UNIQUEIDENTIFIER,
IDKH UNIQUEIDENTIFIER,
IDSP UNIQUEIDENTIFIER,
IDGH UNIQUEIDENTIFIER,
IDKM  UNIQUEIDENTIFIER,
NGAYTAOHOADON DATE DEFAULT NULL,
NGAYDUTINH DATE DEFAULT NULL,
NGAYGIAOHANG DATE DEFAULT NULL,
NGAYNHANHANG DATE DEFAULT NULL,
NGAYTHANHTOAN DATE DEFAULT NULL,
TENSANPHAM NVARCHAR(100) DEFAULT NULL,
SOLUONG INT,
DONGIA DECIMAL(20,0) DEFAULT 0,
KHUYENMAI DECIMAL(20,0) DEFAULT 0,
THANHTIEN DECIMAL(20,0) DEFAULT 0,
TENNGUOINHAN NVARCHAR(50) DEFAULT NULL,
DAICHI NVARCHAR(100) DEFAULT NULL,
SDT VARCHAR(30) DEFAULT NULL,
TRANGTHAI INT DEFAULT 0,
)
ALTER TABLE HOADONDATHANG ADD FOREIGN KEY(IDNV) REFERENCES NHANVIEN(ID)
ALTER TABLE HOADONDATHANG ADD FOREIGN KEY(IDKH) REFERENCES KhachHang(ID)
ALTER TABLE HOADONDATHANG ADD FOREIGN KEY(IDSP) REFERENCES SANPHAM(ID)
ALTER TABLE HOADONDATHANG ADD FOREIGN KEY(IDGH) REFERENCES GIOHANG(ID)
ALTER TABLE HOADONDATHANG ADD FOREIGN KEY(IDKM) REFERENCES KHUYENMAI(ID)

CREATE TABLE HOADONMUAHANG(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IDNV UNIQUEIDENTIFIER,
IDKM  UNIQUEIDENTIFIER,
SOLUONG INT,
NGAYTAOHOADON DATE DEFAULT NULL,
KHUYENMAI DECIMAL(20,0) DEFAULT 0,
TONGTIEN DECIMAL(20,0) DEFAULT 0,
TRANGTHAI INT DEFAULT 0,
)

ALTER TABLE HOADONMUAHANG ADD FOREIGN KEY(IDNV) REFERENCES NHANVIEN(ID)
ALTER TABLE HOADONMUAHANG ADD FOREIGN KEY(IDKM) REFERENCES KHUYENMAI(ID)

CREATE TABLE HOADONCHITIET(
IDHOADONMUAHANG UNIQUEIDENTIFIER,
IDSP UNIQUEIDENTIFIER,
SoLuong INT,
DonGia DECIMAL(20,0) DEFAULT 0,
CONSTRAINT PK_HOADONCHITIET PRIMARY KEY (IDHOADONMUAHANG,IDSP),
CONSTRAINT FK3 FOREIGN KEY(IDHOADONMUAHANG) REFERENCES HOADONMUAHANG(ID),
CONSTRAINT FK4 FOREIGN KEY(IDSP) REFERENCES SANPHAM(ID),
)